<div data-id="<#=image.id#>"
	 data-caption="<#=image.caption ? image.caption : ''#>"
	 data-position="<#=imageObj.getImagePosition(image)#>"
	 data-index="<#=index#>" class="thrv_wrapper tve_image_caption tve-draggable tve-droppable <#=captionSettings.position ? captionSettings.position.classes : ''#> <#=image.styleClass#>"
	 draggable="true">
	<span class="tve_image_frame">
	<#if(imageLinks.length && imageLinks[index] && imageLinks[index].hasLink){#>
	<a href="<#=imageLinks[index].href#>" target="<#=imageLinks[index].target#>" rel="<#=imageLinks[index].rel#>">
	<# } #>
		<img class="tve_image wp-image-<#=image.id#>"
			 alt="<#=image.alt#>"
			 data-id="<#=image.id#>"
			 width="<#=image.width#>"
			 height="<#=image.height#>"
			 title="<#=image.title#>"
			 src="<#=image.sizes[imageObj.oldImageSize] ? image.sizes[imageObj.oldImageSize].url : image.url #>"
			 data-src="<#=image.sizes[imageObj.getFullwidthSize()] ? image.sizes[imageObj.getFullwidthSize()].url : image.url#>"
			 loading="lazy"
			 draggable="false">
	<#if(imageLinks.length && imageLinks[index] && imageLinks[index].hasLink){#>
	</a>
	<# } #>
	</span>
	<# if(imageObj.hasCaptions()){#>
	<p class="thrv_wrapper wp-caption-text thrv-inline-text tve-froala fr-box fr-basic <#= captionSettings.alignment ? captionSettings.alignment.classes : '' #>"
	<#= captionSettings.position ? captionSettings.position.attr : '' #>
	<#= captionSettings.alignment ? captionSettings.alignment.attr : '' #>
	>
	<#if(captionLinks.length && captionLinks[index] && captionLinks[index].hasLink){#>
	<a href="<#=captionLinks[index].href#>" target="<#=captionLinks[index].target#>" rel="<#=captionLinks[index].rel#>">
		<# } #>
		<#=image.caption ? image.caption : '&nbsp;'#>
		<#if(captionLinks.length && captionLinks[index] && captionLinks[index].hasLink){#>
	</a>
	<# } #>
	</p>
	<# } #>

</div>